### ISSUE TITLE
Save Data Restore crashing after loading old NAND Backup

### ISSUE THREAD

**Issue by TopKek69420** [WerWolv98/EdiZon#27]
I restored an old NAND Backup and batch dumped all my saves. Unfortunately, selecting the Restore option only crashes my console. No error code or anything. 

1. Batch Backup all saves
2. Restore old NAND
3. Try to restore save

Additional context
I had formatted my console and the NAND Backup is from before the format. Running latest ReiNX + fs_mitm.kip.

**Comment by WerWolv98** [comment]
For some games (especially for ones with large save files like BOTW) it takes several seconds for the restore to finish. How long did you wait? Also you might want to try Hekate and tomGER's atmosphere files instead of ReiNX. It sounds like an FS error

**Comment by TopKek69420** [comment]
It would not even let me select the save I want to restore for a game, so that was not the problem. It seems to work fine under Hekate + SDFiles though.
