### ISSUE TITLE
update make the edizon damaged

### ISSUE THREAD

**Issue by Xianbei233** [WerWolv98/EdiZon#34]
**Describe the bug**
press the "-" for a while for update, it seems nothing happened. Then get error that need me reboot and edizon get damaged, version back to 1.0.0. opening it will cause the reboot error 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: SDFiles V10

 - Version: 6.0.1

**Comment by WerWolv98** [comment]
Reboot error? Is your console crashing? If so, what error code are you getting? Also, could you upload your EdiZon.nro? My server seems to be alright

**Comment by Xianbei233** [comment]
emmmmm,yes, the console crashing,the error code i don't remember , but it mentioned me file broke or something failed and to press the power button 12 seconds to reboot the console. This error has been happened several times after i use sdfile v10. I think it's just the cfw unstable. But after i update edizon failed and file broken, lauching edizon  will certainly cause the error

**Comment by WerWolv98** [comment]
I need the exact error code to help you.  Honestly sounds like somehow your sd card got corrupted by the update. Are you using exFAT?

**Comment by Xianbei233** [comment]
I delete the broken edizon files through nx-shell and reinstall it through appstore without any update operation

**Comment by WerWolv98** [comment]
That's not an edizon error, it's the hbmenu complaining that the nro is bad
