### ISSUE TITLE
GUI: stepSize is ignored with parsing configuration file

### ISSUE THREAD

**Issue by kindofblues** [WerWolv98/EdiZon#36]
**Describe the bug**
The step size in the bottom left corner of the GUI is not updated when scrolling to an item whose "stepSize" property is set to something different than 1.

**To Reproduce**
Scroll to an item whose stepSize is different than 1 in the configuration file, for example, Banana Coins in Donkey Kong: Tropical Freeze (stepSize = 10).

**Expected behavior**
The GUI does not show the correct value in the bottom left corner (1). However, the quantity is incremented by the correct amount (10) when using the arrow keys.

**Additional context**
Tested with Edizon 1.5.1
Atmosphere 0.8.1
FW 6.2.0

**Comment by WerWolv98** [comment]
This is actually intended behavior because the step size is meant as a multiplier to the increase amount and not the amount itself.
