### ISSUE TITLE
Update button makes the program freeze

### ISSUE THREAD

**Issue by Dxnielo** [WerWolv98/EdiZon#37]
I tried pressing - to see what Update did and it froze, and my .nro file is corrupted

1. Go in the hb menu
2. Click on EdiZon
3. Press -

I was just curious in what it did ( if it updated the game or the program)

Bug ocured on:
 - Atmosphere 0.8.2
 - CFW 6.2.0
 - Edizon 1.5.1 (latest)

**Comment by WerWolv98** [comment]
Sounds to me like you either go a connection error or you didn't wait long enough while the update was happening. EdiZon freezes up while doing the update but it shouldn't take more than 10 seconds max when doing so

**Comment by Dxnielo** [comment]
Ooooh, okay, thank you for the clarification, I'm just impatient.
